version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7028:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=ECommrce;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
